version: '3.5'
services:
  rails_api:
    container_name: rails_api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: rails_api
    working_dir: /app/api
    volumes:
      - .:/app
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - database
    ports:
      - 7770:7770
    env_file:
      - ./api/.env.local
  react_client:
    container_name: react_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react_client
    working_dir: /home/node/app/client
    volumes:
      - ./:/home/node/app
    ports:
      - 7771:7771
    env_file:
      - ./client/.env
  database:
    container_name: postgres_db
    image: postgres:9.6
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 7772:5432
    env_file:
      - ./api/.env.local
volumes:
  database:
